service: aws-coldstart-python

provider:
  name: aws
  runtime: python3.6
  versionFunctions: false

functions:
  memory-128:
    handler: handler.hello
    memorySize: 128

  memory-256:
    handler: handler.hello
    memorySize: 256

  memory-512:
    handler: handler.hello
    memorySize: 512

  memory-1024:
    handler: handler.hello
    memorySize: 1024

  memory-1536:
    handler: handler.hello
    memorySize: 1536