service: aws-coldstart-nodejs6-package-size

provider:
  name: aws
  runtime: nodejs4.3
  versionFunctions: false

package:
  individually: true
  exclude:
    - no-deps/**
    - bluebird-only/**
    - bluebird-lodash-only/**
    - large-deps/**
    - extra-large-deps/**
    - extra-extra-large-deps/**
    - extra-extra-extra-large-deps/**
    - ping/**

functions:
  no-deps-128:
    handler: no-deps/handler.handler
    memorySize: 128
    package:
      include:
        - no-deps/**
  no-deps-256:
    handler: no-deps/handler.handler
    memorySize: 256
    package:
      include:
        - no-deps/**
  no-deps-512:
    handler: no-deps/handler.handler
    memorySize: 512
    package:
      include:
        - no-deps/**
  no-deps-1024:
    handler: no-deps/handler.handler
    memorySize: 1024
    package:
      include:
        - no-deps/**
  no-deps-1536:
    handler: no-deps/handler.handler
    memorySize: 1536
    package:
      include:
        - no-deps/**

  bluebird-only-128:
    handler: bluebird-only/handler.handler
    memorySize: 128
    package:
      include:
        - bluebird-only/**
  bluebird-only-256:
    handler: bluebird-only/handler.handler
    memorySize: 256
    package:
      include:
        - bluebird-only/**
  bluebird-only-512:
    handler: bluebird-only/handler.handler
    memorySize: 512
    package:
      include:
        - bluebird-only/**
  bluebird-only-1024:
    handler: bluebird-only/handler.handler
    memorySize: 1024
    package:
      include:
        - bluebird-only/**
  bluebird-only-1536:
    handler: bluebird-only/handler.handler
    memorySize: 1536
    package:
      include:
        - bluebird-only/**

  bluebird-lodash-only-128:
    handler: bluebird-lodash-only/handler.handler
    memorySize: 128
    package:
      include:
        - bluebird-lodash-only/**
  bluebird-lodash-only-256:
    handler: bluebird-lodash-only/handler.handler
    memorySize: 256
    package:
      include:
        - bluebird-lodash-only/**
  bluebird-lodash-only-512:
    handler: bluebird-lodash-only/handler.handler
    memorySize: 512
    package:
      include:
        - bluebird-lodash-only/**
  bluebird-lodash-only-1024:
    handler: bluebird-lodash-only/handler.handler
    memorySize: 1024
    package:
      include:
        - bluebird-lodash-only/**
  bluebird-lodash-only-1536:
    handler: bluebird-lodash-only/handler.handler
    memorySize: 1536
    package:
      include:
        - bluebird-lodash-only/**

  L-deps-128:
    handler: large-deps/handler.handler
    memorySize: 128
    package:
      include:
        - large-deps/**
  L-deps-256:
    handler: large-deps/handler.handler
    memorySize: 256
    package:
      include:
        - large-deps/**
  L-deps-512:
    handler: large-deps/handler.handler
    memorySize: 512
    package:
      include:
        - large-deps/**
  L-deps-1024:
    handler: large-deps/handler.handler
    memorySize: 1024
    package:
      include:
        - large-deps/**
  L-deps-1536:
    handler: large-deps/handler.handler
    memorySize: 1536
    package:
      include:
        - large-deps/**

  XL-deps-128:
    handler: extra-large-deps/handler.handler
    memorySize: 128
    package:
      include:
        - extra-large-deps/**
  XL-deps-256:
    handler: extra-large-deps/handler.handler
    memorySize: 256
    package:
      include:
        - extra-large-deps/**
  XL-deps-512:
    handler: extra-large-deps/handler.handler
    memorySize: 512
    package:
      include:
        - extra-large-deps/**
  XL-deps-1024:
    handler: extra-large-deps/handler.handler
    memorySize: 1024
    package:
      include:
        - extra-large-deps/**
  XL-deps-1536:
    handler: extra-large-deps/handler.handler
    memorySize: 1536
    package:
      include:
        - extra-large-deps/**

  XXL-deps-128:
    handler: extra-extra-large-deps/handler.handler
    memorySize: 128
    package:
      include:
        - extra-extra-large-deps/**
  XXL-deps-256:
    handler: extra-extra-large-deps/handler.handler
    memorySize: 256
    package:
      include:
        - extra-extra-large-deps/**
  XXL-deps-512:
    handler: extra-extra-large-deps/handler.handler
    memorySize: 512
    package:
      include:
        - extra-extra-large-deps/**
  XXL-deps-1024:
    handler: extra-extra-large-deps/handler.handler
    memorySize: 1024
    package:
      include:
        - extra-extra-large-deps/**
  XXL-deps-1536:
    handler: extra-extra-large-deps/handler.handler
    memorySize: 1536
    package:
      include:
        - extra-extra-large-deps/**

  XXXL-deps-128:
    handler: extra-extra-extra-large-deps/handler.handler
    memorySize: 128
    package:
      include:
        - extra-extra-extra-large-deps/**
  XXXL-deps-256:
    handler: extra-extra-extra-large-deps/handler.handler
    memorySize: 256
    package:
      include:
        - extra-extra-extra-large-deps/**
  XXXL-deps-512:
    handler: extra-extra-extra-large-deps/handler.handler
    memorySize: 512
    package:
      include:
        - extra-extra-extra-large-deps/**
  XXXL-deps-1024:
    handler: extra-extra-extra-large-deps/handler.handler
    memorySize: 1024
    package:
      include:
        - extra-extra-extra-large-deps/**
  XXXL-deps-1536:
    handler: extra-extra-extra-large-deps/handler.handler
    memorySize: 1536
    package:
      include:
        - extra-extra-extra-large-deps/**